#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManager.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="HeQuanTriCSDL")]
	public partial class dbEventsManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietCT(ChiTietCT instance);
    partial void UpdateChiTietCT(ChiTietCT instance);
    partial void DeleteChiTietCT(ChiTietCT instance);
    partial void InsertPhiPhat(PhiPhat instance);
    partial void UpdatePhiPhat(PhiPhat instance);
    partial void DeletePhiPhat(PhiPhat instance);
    partial void InsertChuongTrinh(ChuongTrinh instance);
    partial void UpdateChuongTrinh(ChuongTrinh instance);
    partial void DeleteChuongTrinh(ChuongTrinh instance);
    partial void InsertKeHoachChiTra(KeHoachChiTra instance);
    partial void UpdateKeHoachChiTra(KeHoachChiTra instance);
    partial void DeleteKeHoachChiTra(KeHoachChiTra instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    #endregion
		
		public dbEventsManagementDataContext() : 
				base(global::EventManager.Properties.Settings.Default.ConnectString, mappingSource)
		{
			OnCreated();
		}
		
		public dbEventsManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbEventsManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbEventsManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbEventsManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietCT> ChiTietCTs
		{
			get
			{
				return this.GetTable<ChiTietCT>();
			}
		}
		
		public System.Data.Linq.Table<PhiPhat> PhiPhats
		{
			get
			{
				return this.GetTable<PhiPhat>();
			}
		}
		
		public System.Data.Linq.Table<ChuongTrinh> ChuongTrinhs
		{
			get
			{
				return this.GetTable<ChuongTrinh>();
			}
		}
		
		public System.Data.Linq.Table<KeHoachChiTra> KeHoachChiTras
		{
			get
			{
				return this.GetTable<KeHoachChiTra>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<view_ThongTinKH> view_ThongTinKHs
		{
			get
			{
				return this.GetTable<view_ThongTinKH>();
			}
		}
		
		public System.Data.Linq.Table<view_ThongTinNV> view_ThongTinNVs
		{
			get
			{
				return this.GetTable<view_ThongTinNV>();
			}
		}
		
		[Function(Name="dbo.sp_suaChuongTrinh")]
		public int sp_suaChuongTrinh([Parameter(Name="MaCT", DbType="VarChar(5)")] string maCT, [Parameter(Name="TenCT", DbType="NVarChar(50)")] string tenCT, [Parameter(Name="MoTa", DbType="NVarChar(100)")] string moTa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCT, tenCT, moTa);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_xoaNhanVien")]
		public int sp_xoaNhanVien([Parameter(Name="MaNV", DbType="VarChar(5)")] string maNV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_suaKhachHang")]
		public int sp_suaKhachHang([Parameter(Name="MaKH", DbType="VarChar(8)")] string maKH, [Parameter(Name="TenKH", DbType="NVarChar(50)")] string tenKH, [Parameter(Name="DiaChi", DbType="NVarChar(100)")] string diaChi, [Parameter(Name="DienThoai", DbType="VarChar(20)")] string dienThoai, [Parameter(Name="Email", DbType="VarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH, tenKH, diaChi, dienThoai, email);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_suaNhanVien")]
		public int sp_suaNhanVien([Parameter(Name="MaNV", DbType="VarChar(5)")] string maNV, [Parameter(Name="TenNV", DbType="NVarChar(50)")] string tenNV, [Parameter(Name="GioiTinh", DbType="Bit")] System.Nullable<bool> gioiTinh, [Parameter(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [Parameter(Name="DiaChi", DbType="NVarChar(100)")] string diaChi, [Parameter(Name="DienThoai", DbType="VarChar(20)")] string dienThoai, [Parameter(Name="Email", DbType="VarChar(50)")] string email, [Parameter(Name="HeSoLuong", DbType="Float")] System.Nullable<double> heSoLuong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, tenNV, gioiTinh, ngaySinh, diaChi, dienThoai, email, heSoLuong);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_thanhToan")]
		public int sp_thanhToan([Parameter(Name="IdCTCT", DbType="Int")] System.Nullable<int> idCTCT, [Parameter(Name="GiaiDoan", DbType="TinyInt")] System.Nullable<byte> giaiDoan, [Parameter(Name="NgayThatSuTT", DbType="SmallDateTime")] System.Nullable<System.DateTime> ngayThatSuTT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCTCT, giaiDoan, ngayThatSuTT);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_themChiTietCT")]
		public int sp_themChiTietCT([Parameter(Name="MaKH", DbType="VarChar(8)")] string maKH, [Parameter(Name="MaCT", DbType="VarChar(5)")] string maCT, [Parameter(Name="MaNV", DbType="VarChar(5)")] string maNV, [Parameter(Name="NgayBatDau", DbType="SmallDateTime")] System.Nullable<System.DateTime> ngayBatDau, [Parameter(Name="NgayKetThuc", DbType="SmallDateTime")] System.Nullable<System.DateTime> ngayKetThuc, [Parameter(Name="SoNguoiThamGia", DbType="Int")] System.Nullable<int> soNguoiThamGia, [Parameter(Name="MucPhat", DbType="Int")] System.Nullable<int> mucPhat, [Parameter(Name="DiaDiem", DbType="NVarChar(100)")] string diaDiem, [Parameter(Name="MoTa", DbType="NVarChar(100)")] string moTa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH, maCT, maNV, ngayBatDau, ngayKetThuc, soNguoiThamGia, mucPhat, diaDiem, moTa);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_themChuongTrinh")]
		public int sp_themChuongTrinh([Parameter(Name="MaCT", DbType="VarChar(5)")] string maCT, [Parameter(Name="TenCT", DbType="NVarChar(50)")] string tenCT, [Parameter(Name="MoTa", DbType="NVarChar(100)")] string moTa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCT, tenCT, moTa);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_themKeHoachChiTra")]
		public int sp_themKeHoachChiTra([Parameter(Name="IdCTCT", DbType="Int")] System.Nullable<int> idCTCT, [Parameter(Name="GiaiDoan", DbType="TinyInt")] System.Nullable<byte> giaiDoan, [Parameter(Name="Phi", DbType="Int")] System.Nullable<int> phi, [Parameter(Name="NgayTTTheoKH", DbType="SmallDateTime")] System.Nullable<System.DateTime> ngayTTTheoKH, [Parameter(Name="MoTaPhi", DbType="NVarChar(100)")] string moTaPhi, [Parameter(Name="PhuongThucTT", DbType="NVarChar(50)")] string phuongThucTT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCTCT, giaiDoan, phi, ngayTTTheoKH, moTaPhi, phuongThucTT);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_themKhachHang")]
		public int sp_themKhachHang([Parameter(Name="MaKH", DbType="VarChar(8)")] string maKH, [Parameter(Name="TenKH", DbType="NVarChar(50)")] string tenKH, [Parameter(Name="DiaChi", DbType="NVarChar(100)")] string diaChi, [Parameter(Name="DienThoai", DbType="VarChar(20)")] string dienThoai, [Parameter(Name="Email", DbType="VarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH, tenKH, diaChi, dienThoai, email);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_themNhanVien")]
		public int sp_themNhanVien([Parameter(Name="MaNV", DbType="VarChar(5)")] string maNV, [Parameter(Name="TenNV", DbType="NVarChar(50)")] string tenNV, [Parameter(Name="GioiTinh", DbType="Bit")] System.Nullable<bool> gioiTinh, [Parameter(Name="NgaySinh", DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [Parameter(Name="DiaChi", DbType="NVarChar(100)")] string diaChi, [Parameter(Name="DienThoai", DbType="VarChar(20)")] string dienThoai, [Parameter(Name="Email", DbType="VarChar(50)")] string email, [Parameter(Name="HeSoLuong", DbType="Float")] System.Nullable<double> heSoLuong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNV, tenNV, gioiTinh, ngaySinh, diaChi, dienThoai, email, heSoLuong);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_tongNo")]
		public int sp_tongNo([Parameter(DbType="VarChar(8)")] string maKH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_xoaChuongTrinh")]
		public int sp_xoaChuongTrinh([Parameter(Name="MaCT", DbType="VarChar(5)")] string maCT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCT);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_xoaKhachHang")]
		public int sp_xoaKhachHang([Parameter(Name="MaKH", DbType="VarChar(5)")] string maKH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.fc_demSoLanPhat", IsComposable=true)]
		public System.Nullable<int> fc_demSoLanPhat([Parameter(DbType="VarChar(8)")] string maKH)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH).ReturnValue));
		}
		
		[Function(Name="dbo.fc_TongPhiChuaThanhToan", IsComposable=true)]
		public System.Nullable<int> fc_TongPhiChuaThanhToan([Parameter(Name="IdCTCT", DbType="Int")] System.Nullable<int> idCTCT)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCTCT).ReturnValue));
		}
		
		[Function(Name="dbo.fc_TongNo", IsComposable=true)]
		public System.Nullable<int> fc_TongNo([Parameter(DbType="VarChar(8)")] string maKH)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH).ReturnValue));
		}
		
		[Function(Name="dbo.fc_TongPhi", IsComposable=true)]
		public System.Nullable<int> fc_TongPhi([Parameter(DbType="VarChar(8)")] string maKH)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH).ReturnValue));
		}
		
		[Function(Name="dbo.fc_thongTinHD", IsComposable=true)]
		public IQueryable<fc_thongTinHDResult> fc_thongTinHD([Parameter(DbType="VarChar(8)")] string maKH)
		{
			return this.CreateMethodCallQuery<fc_thongTinHDResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH);
		}
		
		[Function(Name="dbo.sp_chuongTrinhTrongNgay")]
		public ISingleResult<sp_chuongTrinhTrongNgayResult> sp_chuongTrinhTrongNgay([Parameter(DbType="SmallDateTime")] System.Nullable<System.DateTime> ngay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngay);
			return ((ISingleResult<sp_chuongTrinhTrongNgayResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_thongKeKH")]
		public ISingleResult<sp_thongKeKHResult> sp_thongKeKH()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_thongKeKHResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_ThanhToanCanThuTuan")]
		public ISingleResult<sp_ThanhToanCanThuTuanResult> sp_ThanhToanCanThuTuan([Parameter(DbType="Date")] System.Nullable<System.DateTime> ngay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngay);
			return ((ISingleResult<sp_ThanhToanCanThuTuanResult>)(result.ReturnValue));
		}
	}
	
	[Table(Name="dbo.ChiTietCT")]
	public partial class ChiTietCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaKH;
		
		private string _MaCT;
		
		private string _MaNV;
		
		private System.DateTime _NgayBatDau;
		
		private System.DateTime _NgayKetThuc;
		
		private string _MoTa;
		
		private System.Nullable<int> _SoNguoiThamGia;
		
		private string _DiaDiem;
		
		private int _MucPhat;
		
		private EntitySet<KeHoachChiTra> _KeHoachChiTras;
		
		private EntityRef<ChuongTrinh> _ChuongTrinh;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(System.DateTime value);
    partial void OnNgayKetThucChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnSoNguoiThamGiaChanging(System.Nullable<int> value);
    partial void OnSoNguoiThamGiaChanged();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnMucPhatChanging(int value);
    partial void OnMucPhatChanged();
    #endregion
		
		public ChiTietCT()
		{
			this._KeHoachChiTras = new EntitySet<KeHoachChiTra>(new Action<KeHoachChiTra>(this.attach_KeHoachChiTras), new Action<KeHoachChiTra>(this.detach_KeHoachChiTras));
			this._ChuongTrinh = default(EntityRef<ChuongTrinh>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_MaKH", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[Column(Storage="_MaCT", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					if (this._ChuongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[Column(Storage="_MaNV", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[Column(Storage="_NgayBatDau", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[Column(Storage="_NgayKetThuc", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[Column(Storage="_MoTa", DbType="NVarChar(100)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[Column(Storage="_SoNguoiThamGia", DbType="Int")]
		public System.Nullable<int> SoNguoiThamGia
		{
			get
			{
				return this._SoNguoiThamGia;
			}
			set
			{
				if ((this._SoNguoiThamGia != value))
				{
					this.OnSoNguoiThamGiaChanging(value);
					this.SendPropertyChanging();
					this._SoNguoiThamGia = value;
					this.SendPropertyChanged("SoNguoiThamGia");
					this.OnSoNguoiThamGiaChanged();
				}
			}
		}
		
		[Column(Storage="_DiaDiem", DbType="NVarChar(100)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[Column(Storage="_MucPhat", DbType="Int NOT NULL")]
		public int MucPhat
		{
			get
			{
				return this._MucPhat;
			}
			set
			{
				if ((this._MucPhat != value))
				{
					this.OnMucPhatChanging(value);
					this.SendPropertyChanging();
					this._MucPhat = value;
					this.SendPropertyChanged("MucPhat");
					this.OnMucPhatChanged();
				}
			}
		}
		
		[Association(Name="ChiTietCT_KeHoachChiTra", Storage="_KeHoachChiTras", ThisKey="ID", OtherKey="IdCTCT")]
		public EntitySet<KeHoachChiTra> KeHoachChiTras
		{
			get
			{
				return this._KeHoachChiTras;
			}
			set
			{
				this._KeHoachChiTras.Assign(value);
			}
		}
		
		[Association(Name="ChuongTrinh_ChiTietCT", Storage="_ChuongTrinh", ThisKey="MaCT", OtherKey="MaCT", IsForeignKey=true)]
		public ChuongTrinh ChuongTrinh
		{
			get
			{
				return this._ChuongTrinh.Entity;
			}
			set
			{
				ChuongTrinh previousValue = this._ChuongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._ChuongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuongTrinh.Entity = null;
						previousValue.ChiTietCTs.Remove(this);
					}
					this._ChuongTrinh.Entity = value;
					if ((value != null))
					{
						value.ChiTietCTs.Add(this);
						this._MaCT = value.MaCT;
					}
					else
					{
						this._MaCT = default(string);
					}
					this.SendPropertyChanged("ChuongTrinh");
				}
			}
		}
		
		[Association(Name="KhachHang_ChiTietCT", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.ChiTietCTs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietCTs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[Association(Name="NhanVien_ChiTietCT", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ChiTietCTs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ChiTietCTs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KeHoachChiTras(KeHoachChiTra entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietCT = this;
		}
		
		private void detach_KeHoachChiTras(KeHoachChiTra entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietCT = null;
		}
	}
	
	[Table(Name="dbo.PhiPhat")]
	public partial class PhiPhat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCTCT;
		
		private byte _GiaiDoan;
		
		private int _PhiPhat1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCTCTChanging(int value);
    partial void OnIdCTCTChanged();
    partial void OnGiaiDoanChanging(byte value);
    partial void OnGiaiDoanChanged();
    partial void OnPhiPhat1Changing(int value);
    partial void OnPhiPhat1Changed();
    #endregion
		
		public PhiPhat()
		{
			OnCreated();
		}
		
		[Column(Storage="_IdCTCT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCTCT
		{
			get
			{
				return this._IdCTCT;
			}
			set
			{
				if ((this._IdCTCT != value))
				{
					this.OnIdCTCTChanging(value);
					this.SendPropertyChanging();
					this._IdCTCT = value;
					this.SendPropertyChanged("IdCTCT");
					this.OnIdCTCTChanged();
				}
			}
		}
		
		[Column(Storage="_GiaiDoan", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte GiaiDoan
		{
			get
			{
				return this._GiaiDoan;
			}
			set
			{
				if ((this._GiaiDoan != value))
				{
					this.OnGiaiDoanChanging(value);
					this.SendPropertyChanging();
					this._GiaiDoan = value;
					this.SendPropertyChanged("GiaiDoan");
					this.OnGiaiDoanChanged();
				}
			}
		}
		
		[Column(Name="PhiPhat", Storage="_PhiPhat1", DbType="Int NOT NULL")]
		public int PhiPhat1
		{
			get
			{
				return this._PhiPhat1;
			}
			set
			{
				if ((this._PhiPhat1 != value))
				{
					this.OnPhiPhat1Changing(value);
					this.SendPropertyChanging();
					this._PhiPhat1 = value;
					this.SendPropertyChanged("PhiPhat1");
					this.OnPhiPhat1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ChuongTrinh")]
	public partial class ChuongTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCT;
		
		private string _TenCT;
		
		private string _MoTaCT;
		
		private EntitySet<ChiTietCT> _ChiTietCTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnTenCTChanging(string value);
    partial void OnTenCTChanged();
    partial void OnMoTaCTChanging(string value);
    partial void OnMoTaCTChanged();
    #endregion
		
		public ChuongTrinh()
		{
			this._ChiTietCTs = new EntitySet<ChiTietCT>(new Action<ChiTietCT>(this.attach_ChiTietCTs), new Action<ChiTietCT>(this.detach_ChiTietCTs));
			OnCreated();
		}
		
		[Column(Storage="_MaCT", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[Column(Storage="_TenCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCT
		{
			get
			{
				return this._TenCT;
			}
			set
			{
				if ((this._TenCT != value))
				{
					this.OnTenCTChanging(value);
					this.SendPropertyChanging();
					this._TenCT = value;
					this.SendPropertyChanged("TenCT");
					this.OnTenCTChanged();
				}
			}
		}
		
		[Column(Storage="_MoTaCT", DbType="NVarChar(100)")]
		public string MoTaCT
		{
			get
			{
				return this._MoTaCT;
			}
			set
			{
				if ((this._MoTaCT != value))
				{
					this.OnMoTaCTChanging(value);
					this.SendPropertyChanging();
					this._MoTaCT = value;
					this.SendPropertyChanged("MoTaCT");
					this.OnMoTaCTChanged();
				}
			}
		}
		
		[Association(Name="ChuongTrinh_ChiTietCT", Storage="_ChiTietCTs", ThisKey="MaCT", OtherKey="MaCT")]
		public EntitySet<ChiTietCT> ChiTietCTs
		{
			get
			{
				return this._ChiTietCTs;
			}
			set
			{
				this._ChiTietCTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietCTs(ChiTietCT entity)
		{
			this.SendPropertyChanging();
			entity.ChuongTrinh = this;
		}
		
		private void detach_ChiTietCTs(ChiTietCT entity)
		{
			this.SendPropertyChanging();
			entity.ChuongTrinh = null;
		}
	}
	
	[Table(Name="dbo.KeHoachChiTra")]
	public partial class KeHoachChiTra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCTCT;
		
		private byte _GiaiDoan;
		
		private int _Phi;
		
		private string _MoTaPhi;
		
		private string _PhuongThucTT;
		
		private System.DateTime _NgayTTTheoKH;
		
		private System.Nullable<System.DateTime> _NgayThatSuTT;
		
		private EntityRef<ChiTietCT> _ChiTietCT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCTCTChanging(int value);
    partial void OnIdCTCTChanged();
    partial void OnGiaiDoanChanging(byte value);
    partial void OnGiaiDoanChanged();
    partial void OnPhiChanging(int value);
    partial void OnPhiChanged();
    partial void OnMoTaPhiChanging(string value);
    partial void OnMoTaPhiChanged();
    partial void OnPhuongThucTTChanging(string value);
    partial void OnPhuongThucTTChanged();
    partial void OnNgayTTTheoKHChanging(System.DateTime value);
    partial void OnNgayTTTheoKHChanged();
    partial void OnNgayThatSuTTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThatSuTTChanged();
    #endregion
		
		public KeHoachChiTra()
		{
			this._ChiTietCT = default(EntityRef<ChiTietCT>);
			OnCreated();
		}
		
		[Column(Storage="_IdCTCT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCTCT
		{
			get
			{
				return this._IdCTCT;
			}
			set
			{
				if ((this._IdCTCT != value))
				{
					if (this._ChiTietCT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCTCTChanging(value);
					this.SendPropertyChanging();
					this._IdCTCT = value;
					this.SendPropertyChanged("IdCTCT");
					this.OnIdCTCTChanged();
				}
			}
		}
		
		[Column(Storage="_GiaiDoan", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte GiaiDoan
		{
			get
			{
				return this._GiaiDoan;
			}
			set
			{
				if ((this._GiaiDoan != value))
				{
					this.OnGiaiDoanChanging(value);
					this.SendPropertyChanging();
					this._GiaiDoan = value;
					this.SendPropertyChanged("GiaiDoan");
					this.OnGiaiDoanChanged();
				}
			}
		}
		
		[Column(Storage="_Phi", DbType="Int NOT NULL")]
		public int Phi
		{
			get
			{
				return this._Phi;
			}
			set
			{
				if ((this._Phi != value))
				{
					this.OnPhiChanging(value);
					this.SendPropertyChanging();
					this._Phi = value;
					this.SendPropertyChanged("Phi");
					this.OnPhiChanged();
				}
			}
		}
		
		[Column(Storage="_MoTaPhi", DbType="NVarChar(100)")]
		public string MoTaPhi
		{
			get
			{
				return this._MoTaPhi;
			}
			set
			{
				if ((this._MoTaPhi != value))
				{
					this.OnMoTaPhiChanging(value);
					this.SendPropertyChanging();
					this._MoTaPhi = value;
					this.SendPropertyChanged("MoTaPhi");
					this.OnMoTaPhiChanged();
				}
			}
		}
		
		[Column(Storage="_PhuongThucTT", DbType="NVarChar(50)")]
		public string PhuongThucTT
		{
			get
			{
				return this._PhuongThucTT;
			}
			set
			{
				if ((this._PhuongThucTT != value))
				{
					this.OnPhuongThucTTChanging(value);
					this.SendPropertyChanging();
					this._PhuongThucTT = value;
					this.SendPropertyChanged("PhuongThucTT");
					this.OnPhuongThucTTChanged();
				}
			}
		}
		
		[Column(Storage="_NgayTTTheoKH", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayTTTheoKH
		{
			get
			{
				return this._NgayTTTheoKH;
			}
			set
			{
				if ((this._NgayTTTheoKH != value))
				{
					this.OnNgayTTTheoKHChanging(value);
					this.SendPropertyChanging();
					this._NgayTTTheoKH = value;
					this.SendPropertyChanged("NgayTTTheoKH");
					this.OnNgayTTTheoKHChanged();
				}
			}
		}
		
		[Column(Storage="_NgayThatSuTT", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayThatSuTT
		{
			get
			{
				return this._NgayThatSuTT;
			}
			set
			{
				if ((this._NgayThatSuTT != value))
				{
					this.OnNgayThatSuTTChanging(value);
					this.SendPropertyChanging();
					this._NgayThatSuTT = value;
					this.SendPropertyChanged("NgayThatSuTT");
					this.OnNgayThatSuTTChanged();
				}
			}
		}
		
		[Association(Name="ChiTietCT_KeHoachChiTra", Storage="_ChiTietCT", ThisKey="IdCTCT", OtherKey="ID", IsForeignKey=true)]
		public ChiTietCT ChiTietCT
		{
			get
			{
				return this._ChiTietCT.Entity;
			}
			set
			{
				ChiTietCT previousValue = this._ChiTietCT.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietCT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietCT.Entity = null;
						previousValue.KeHoachChiTras.Remove(this);
					}
					this._ChiTietCT.Entity = value;
					if ((value != null))
					{
						value.KeHoachChiTras.Add(this);
						this._IdCTCT = value.ID;
					}
					else
					{
						this._IdCTCT = default(int);
					}
					this.SendPropertyChanged("ChiTietCT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _Email;
		
		private EntitySet<ChiTietCT> _ChiTietCTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public KhachHang()
		{
			this._ChiTietCTs = new EntitySet<ChiTietCT>(new Action<ChiTietCT>(this.attach_ChiTietCTs), new Action<ChiTietCT>(this.detach_ChiTietCTs));
			OnCreated();
		}
		
		[Column(Storage="_MaKH", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[Column(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[Column(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[Column(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Association(Name="KhachHang_ChiTietCT", Storage="_ChiTietCTs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<ChiTietCT> ChiTietCTs
		{
			get
			{
				return this._ChiTietCTs;
			}
			set
			{
				this._ChiTietCTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietCTs(ChiTietCT entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_ChiTietCTs(ChiTietCT entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[Table(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _Email;
		
		private double _HeSoLuong;
		
		private EntitySet<ChiTietCT> _ChiTietCTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHeSoLuongChanging(double value);
    partial void OnHeSoLuongChanged();
    #endregion
		
		public NhanVien()
		{
			this._ChiTietCTs = new EntitySet<ChiTietCT>(new Action<ChiTietCT>(this.attach_ChiTietCTs), new Action<ChiTietCT>(this.detach_ChiTietCTs));
			OnCreated();
		}
		
		[Column(Storage="_MaNV", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[Column(Storage="_TenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[Column(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[Column(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[Column(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[Column(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_HeSoLuong", DbType="Float NOT NULL")]
		public double HeSoLuong
		{
			get
			{
				return this._HeSoLuong;
			}
			set
			{
				if ((this._HeSoLuong != value))
				{
					this.OnHeSoLuongChanging(value);
					this.SendPropertyChanging();
					this._HeSoLuong = value;
					this.SendPropertyChanged("HeSoLuong");
					this.OnHeSoLuongChanged();
				}
			}
		}
		
		[Association(Name="NhanVien_ChiTietCT", Storage="_ChiTietCTs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<ChiTietCT> ChiTietCTs
		{
			get
			{
				return this._ChiTietCTs;
			}
			set
			{
				this._ChiTietCTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietCTs(ChiTietCT entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ChiTietCTs(ChiTietCT entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[Table(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private string _TenNguoiDung;
		
		private byte _Quyen;
		
		private string _MoTaQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnQuyenChanging(byte value);
    partial void OnQuyenChanged();
    partial void OnMoTaQuyenChanging(string value);
    partial void OnMoTaQuyenChanged();
    #endregion
		
		public NguoiDung()
		{
			OnCreated();
		}
		
		[Column(Storage="_Username", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[Column(Storage="_Password", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_TenNguoiDung", DbType="NVarChar(30)")]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[Column(Storage="_Quyen", DbType="TinyInt NOT NULL")]
		public byte Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[Column(Storage="_MoTaQuyen", DbType="NVarChar(50)")]
		public string MoTaQuyen
		{
			get
			{
				return this._MoTaQuyen;
			}
			set
			{
				if ((this._MoTaQuyen != value))
				{
					this.OnMoTaQuyenChanging(value);
					this.SendPropertyChanging();
					this._MoTaQuyen = value;
					this.SendPropertyChanged("MoTaQuyen");
					this.OnMoTaQuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.view_ThongTinKH")]
	public partial class view_ThongTinKH
	{
		
		private string _MaKH;
		
		private string _TenKH;
		
		private System.Nullable<int> _SoCTDky;
		
		private System.Nullable<int> _TongPhi;
		
		private System.Nullable<int> _SoLanTreHan;
		
		private System.Nullable<int> _TongNo;
		
		private string _XepLoai;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _DiaChi;
		
		public view_ThongTinKH()
		{
		}
		
		[Column(Storage="_MaKH", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[Column(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[Column(Storage="_SoCTDky", DbType="Int")]
		public System.Nullable<int> SoCTDky
		{
			get
			{
				return this._SoCTDky;
			}
			set
			{
				if ((this._SoCTDky != value))
				{
					this._SoCTDky = value;
				}
			}
		}
		
		[Column(Storage="_TongPhi", DbType="Int")]
		public System.Nullable<int> TongPhi
		{
			get
			{
				return this._TongPhi;
			}
			set
			{
				if ((this._TongPhi != value))
				{
					this._TongPhi = value;
				}
			}
		}
		
		[Column(Storage="_SoLanTreHan", DbType="Int")]
		public System.Nullable<int> SoLanTreHan
		{
			get
			{
				return this._SoLanTreHan;
			}
			set
			{
				if ((this._SoLanTreHan != value))
				{
					this._SoLanTreHan = value;
				}
			}
		}
		
		[Column(Storage="_TongNo", DbType="Int")]
		public System.Nullable<int> TongNo
		{
			get
			{
				return this._TongNo;
			}
			set
			{
				if ((this._TongNo != value))
				{
					this._TongNo = value;
				}
			}
		}
		
		[Column(Storage="_XepLoai", DbType="NVarChar(10)")]
		public string XepLoai
		{
			get
			{
				return this._XepLoai;
			}
			set
			{
				if ((this._XepLoai != value))
				{
					this._XepLoai = value;
				}
			}
		}
		
		[Column(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this._DienThoai = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.view_ThongTinNV")]
	public partial class view_ThongTinNV
	{
		
		private string _MaNV;
		
		private string _TenNV;
		
		private System.Nullable<int> _SoCTDky;
		
		public view_ThongTinNV()
		{
		}
		
		[Column(Storage="_MaNV", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[Column(Storage="_TenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this._TenNV = value;
				}
			}
		}
		
		[Column(Storage="_SoCTDky", DbType="Int")]
		public System.Nullable<int> SoCTDky
		{
			get
			{
				return this._SoCTDky;
			}
			set
			{
				if ((this._SoCTDky != value))
				{
					this._SoCTDky = value;
				}
			}
		}
	}
	
	public partial class fc_thongTinHDResult
	{
		
		private int _ID;
		
		private string _TenKH;
		
		private string _TenCT;
		
		private string _TenNV;
		
		private System.DateTime _NgayBatDau;
		
		private System.DateTime _NgayKetThuc;
		
		private string _MoTa;
		
		private System.Nullable<int> _SoNguoiThamGia;
		
		private string _DiaDiem;
		
		private int _MucPhat;
		
		public fc_thongTinHDResult()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[Column(Storage="_TenCT", DbType="NVarChar(50)")]
		public string TenCT
		{
			get
			{
				return this._TenCT;
			}
			set
			{
				if ((this._TenCT != value))
				{
					this._TenCT = value;
				}
			}
		}
		
		[Column(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this._TenNV = value;
				}
			}
		}
		
		[Column(Storage="_NgayBatDau", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[Column(Storage="_NgayKetThuc", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[Column(Storage="_MoTa", DbType="NVarChar(100)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
		
		[Column(Storage="_SoNguoiThamGia", DbType="Int")]
		public System.Nullable<int> SoNguoiThamGia
		{
			get
			{
				return this._SoNguoiThamGia;
			}
			set
			{
				if ((this._SoNguoiThamGia != value))
				{
					this._SoNguoiThamGia = value;
				}
			}
		}
		
		[Column(Storage="_DiaDiem", DbType="NVarChar(100)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[Column(Storage="_MucPhat", DbType="Int NOT NULL")]
		public int MucPhat
		{
			get
			{
				return this._MucPhat;
			}
			set
			{
				if ((this._MucPhat != value))
				{
					this._MucPhat = value;
				}
			}
		}
	}
	
	public partial class sp_chuongTrinhTrongNgayResult
	{
		
		private string _TenCT;
		
		private string _TenKH;
		
		private System.Nullable<int> _SoNguoiThamGia;
		
		private System.DateTime _NgayKetThuc;
		
		private string _DiaDiem;
		
		private int _MucPhat;
		
		private string _TenNV;
		
		public sp_chuongTrinhTrongNgayResult()
		{
		}
		
		[Column(Storage="_TenCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCT
		{
			get
			{
				return this._TenCT;
			}
			set
			{
				if ((this._TenCT != value))
				{
					this._TenCT = value;
				}
			}
		}
		
		[Column(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[Column(Storage="_SoNguoiThamGia", DbType="Int")]
		public System.Nullable<int> SoNguoiThamGia
		{
			get
			{
				return this._SoNguoiThamGia;
			}
			set
			{
				if ((this._SoNguoiThamGia != value))
				{
					this._SoNguoiThamGia = value;
				}
			}
		}
		
		[Column(Storage="_NgayKetThuc", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[Column(Storage="_DiaDiem", DbType="NVarChar(100)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[Column(Storage="_MucPhat", DbType="Int NOT NULL")]
		public int MucPhat
		{
			get
			{
				return this._MucPhat;
			}
			set
			{
				if ((this._MucPhat != value))
				{
					this._MucPhat = value;
				}
			}
		}
		
		[Column(Storage="_TenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this._TenNV = value;
				}
			}
		}
	}
	
	public partial class sp_thongKeKHResult
	{
		
		private string _MaKH;
		
		private string _TenKH;
		
		private System.Nullable<int> _SoCTDky;
		
		private System.Nullable<int> _TongPhi;
		
		private System.Nullable<int> _SoLanTreHan;
		
		private System.Nullable<int> _TongNo;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _DiaChi;
		
		public sp_thongKeKHResult()
		{
		}
		
		[Column(Storage="_MaKH", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[Column(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[Column(Storage="_SoCTDky", DbType="Int")]
		public System.Nullable<int> SoCTDky
		{
			get
			{
				return this._SoCTDky;
			}
			set
			{
				if ((this._SoCTDky != value))
				{
					this._SoCTDky = value;
				}
			}
		}
		
		[Column(Storage="_TongPhi", DbType="Int")]
		public System.Nullable<int> TongPhi
		{
			get
			{
				return this._TongPhi;
			}
			set
			{
				if ((this._TongPhi != value))
				{
					this._TongPhi = value;
				}
			}
		}
		
		[Column(Storage="_SoLanTreHan", DbType="Int")]
		public System.Nullable<int> SoLanTreHan
		{
			get
			{
				return this._SoLanTreHan;
			}
			set
			{
				if ((this._SoLanTreHan != value))
				{
					this._SoLanTreHan = value;
				}
			}
		}
		
		[Column(Storage="_TongNo", DbType="Int")]
		public System.Nullable<int> TongNo
		{
			get
			{
				return this._TongNo;
			}
			set
			{
				if ((this._TongNo != value))
				{
					this._TongNo = value;
				}
			}
		}
		
		[Column(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this._DienThoai = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class sp_ThanhToanCanThuTuanResult
	{
		
		private string _MaKH;
		
		private string _TenKH;
		
		private int _IdCTCT;
		
		private byte _GiaiDoan;
		
		private string _NgayTTTheoKH;
		
		private int _Phi;
		
		private string _TenNV;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _DiaChi;
		
		public sp_ThanhToanCanThuTuanResult()
		{
		}
		
		[Column(Storage="_MaKH", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[Column(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[Column(Storage="_IdCTCT", DbType="Int NOT NULL")]
		public int IdCTCT
		{
			get
			{
				return this._IdCTCT;
			}
			set
			{
				if ((this._IdCTCT != value))
				{
					this._IdCTCT = value;
				}
			}
		}
		
		[Column(Storage="_GiaiDoan", DbType="TinyInt NOT NULL")]
		public byte GiaiDoan
		{
			get
			{
				return this._GiaiDoan;
			}
			set
			{
				if ((this._GiaiDoan != value))
				{
					this._GiaiDoan = value;
				}
			}
		}
		
		[Column(Storage="_NgayTTTheoKH", DbType="VarChar(30)")]
		public string NgayTTTheoKH
		{
			get
			{
				return this._NgayTTTheoKH;
			}
			set
			{
				if ((this._NgayTTTheoKH != value))
				{
					this._NgayTTTheoKH = value;
				}
			}
		}
		
		[Column(Storage="_Phi", DbType="Int NOT NULL")]
		public int Phi
		{
			get
			{
				return this._Phi;
			}
			set
			{
				if ((this._Phi != value))
				{
					this._Phi = value;
				}
			}
		}
		
		[Column(Storage="_TenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this._TenNV = value;
				}
			}
		}
		
		[Column(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this._DienThoai = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
